language: java

addons :
  sonarcloud:
    organization: "maximedufrasne-github"

script :
  - mvn org.jacoco-maven-plugin:prepare-agent package sonar:sonar
  -Dsonar.projectKey=maximedufrasne_ipi-java-350-ex \
